import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import React from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MusicRecords2U",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
      </body>
    </html>
  );
}


















/*original version 
import type { Metadata } from "next";
import "./globals.css";

import { Poppins as FontSans } from "next/font/google";
import { cn } from "@/lib/utils"
import React from 'react'
const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-sans",
}); 


export const metadata: Metadata = {
  title: "MusicRecords2U",
  description: "Your Online Music Haven",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
        )}
      >
        {children}
        </body>
    </html>
  );
} */
